######################################################################
#
# caos-dashboard - CAOS dashboard
#
# Copyright © 2016, 2017 INFN - Istituto Nazionale di Fisica Nucleare (Italy)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Author: Fabrizio Chiarello <fabrizio.chiarello@pd.infn.it>
#
######################################################################

FROM buildpack-deps:jessie

LABEL maintainer "Fabrizio Chiarello <fabrizio.chiarello@pd.infn.it>"

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install --no-install-recommends -y \
            apt-transport-https \
            apt-utils \
            build-essential \
            curl \
            dnsutils \
            lsb-release \
            net-tools \
            openssh-server \
            sudo \
            vim

# change root password
RUN echo "root:vagrant" | chpasswd

# setup SSH
RUN mkdir /var/run/sshd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
EXPOSE 22

# setup Vagrant user
RUN groupadd --gid 1000 vagrant && \
    useradd --uid 1000 --gid vagrant --shell /bin/bash --create-home vagrant
RUN echo "vagrant:vagrant" | chpasswd

# setup SUDO
RUN echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# provisioning
RUN curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    echo "deb https://deb.nodesource.com/node_7.x jessie main" > /etc/apt/sources.list.d/nodesource.list

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y nodejs yarn

RUN yarn global add gulp-cli

RUN echo "cd /vagrant" >> /home/vagrant/.profile

CMD ["/usr/sbin/sshd", "-D"]
